2023-09-16 00:36:30,919 INFO    StreamThr :2519239 [internal.py:wandb_internal():86] W&B internal server running at pid: 2519239, started at: 2023-09-16 00:36:30.918058
2023-09-16 00:36:30,920 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: status
2023-09-16 00:36:30,934 INFO    WriterThread:2519239 [datastore.py:open_for_write():85] open: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/run-yce7pjbq.wandb
2023-09-16 00:36:30,935 DEBUG   SenderThread:2519239 [sender.py:send():379] send: header
2023-09-16 00:36:31,014 DEBUG   SenderThread:2519239 [sender.py:send():379] send: run
2023-09-16 00:36:31,387 INFO    SenderThread:2519239 [dir_watcher.py:__init__():211] watching files in: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files
2023-09-16 00:36:31,387 INFO    SenderThread:2519239 [sender.py:_start_run_threads():1121] run started: yce7pjbq with start time 1694820990.917467
2023-09-16 00:36:31,411 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: check_version
2023-09-16 00:36:31,412 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: check_version
2023-09-16 00:36:31,478 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: run_start
2023-09-16 00:36:31,487 DEBUG   HandlerThread:2519239 [system_info.py:__init__():32] System info init
2023-09-16 00:36:31,487 DEBUG   HandlerThread:2519239 [system_info.py:__init__():47] System info init done
2023-09-16 00:36:31,487 INFO    HandlerThread:2519239 [system_monitor.py:start():181] Starting system monitor
2023-09-16 00:36:31,488 INFO    SystemMonitor:2519239 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-16 00:36:31,488 INFO    HandlerThread:2519239 [system_monitor.py:probe():201] Collecting system info
2023-09-16 00:36:31,489 INFO    SystemMonitor:2519239 [interfaces.py:start():190] Started cpu monitoring
2023-09-16 00:36:31,489 INFO    SystemMonitor:2519239 [interfaces.py:start():190] Started disk monitoring
2023-09-16 00:36:31,490 INFO    SystemMonitor:2519239 [interfaces.py:start():190] Started gpu monitoring
2023-09-16 00:36:31,491 INFO    SystemMonitor:2519239 [interfaces.py:start():190] Started memory monitoring
2023-09-16 00:36:31,491 INFO    SystemMonitor:2519239 [interfaces.py:start():190] Started network monitoring
2023-09-16 00:36:31,514 DEBUG   HandlerThread:2519239 [system_info.py:probe():196] Probing system
2023-09-16 00:36:31,524 DEBUG   HandlerThread:2519239 [system_info.py:_probe_git():181] Probing git
2023-09-16 00:36:31,557 DEBUG   HandlerThread:2519239 [system_info.py:_probe_git():189] Probing git done
2023-09-16 00:36:31,557 DEBUG   HandlerThread:2519239 [system_info.py:probe():244] Probing system done
2023-09-16 00:36:31,558 DEBUG   HandlerThread:2519239 [system_monitor.py:probe():210] {'os': 'Linux-5.15.0-76-generic-x86_64-with-glibc2.17', 'python': '3.8.15', 'heartbeatAt': '2023-09-15T23:36:31.514502', 'startedAt': '2023-09-15T23:36:30.892468', 'docker': None, 'cuda': None, 'args': ('--model_name', 'Entangled18', '--project_name', 'Elodea', '--entity', 'frankslab', '--root', '/local/scratch/jrs596/dat/ElodeaProject', '--data_dir', 'FasterRCNN_output/Rudders_split', '--arch', 'resnet18', '--min_epochs', '10', '--max_epochs', '100', '--batch_size', '32', '--patience', '20', '--weights', '/local/scratch/jrs596/dat/models/PlantNotPlant_SemiSup.pkl', '--sweep', '--sweep_config', '/home/userfs/j/jrs596/scripts/Entangled/sweep_config.yml'), 'state': 'running', 'program': '/home/userfs/j/jrs596/scripts/Entangled/Torch_Custom_CNNs2.2.1.py', 'codePathLocal': 'Torch_Custom_CNNs2.2.1.py', 'codePath': 'Torch_Custom_CNNs2.2.1.py', 'git': {'remote': 'git@github.com:jrsykes/Entangled.git', 'commit': 'dd36b1f71e53d67a140ff98d32b01aa90a307e46'}, 'email': 'jamie.sykes@york.ac.uk', 'root': '/home/userfs/j/jrs596/scripts/Entangled', 'host': 'csgpu5', 'username': 'jrs596', 'executable': '/local/scratch/jrs596/envs/Entangled/bin/python', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 3.43725, 'min': 800.0, 'max': 4700.0}, 'cpu_freq_per_core': [{'current': 3.7, 'min': 800.0, 'max': 4700.0}, {'current': 3.7, 'min': 800.0, 'max': 4700.0}, {'current': 3.4, 'min': 800.0, 'max': 4700.0}, {'current': 3.399, 'min': 800.0, 'max': 4700.0}, {'current': 3.399, 'min': 800.0, 'max': 4700.0}, {'current': 3.399, 'min': 800.0, 'max': 4700.0}, {'current': 3.4, 'min': 800.0, 'max': 4700.0}, {'current': 3.4, 'min': 800.0, 'max': 4700.0}, {'current': 3.399, 'min': 800.0, 'max': 4700.0}, {'current': 3.4, 'min': 800.0, 'max': 4700.0}, {'current': 3.399, 'min': 800.0, 'max': 4700.0}, {'current': 3.553, 'min': 800.0, 'max': 4700.0}], 'disk': {'/': {'total': 427.3533935546875, 'used': 26.311935424804688}}, 'gpu': 'NVIDIA GeForce GTX 1080 Ti', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1080 Ti', 'memory_total': 11811160064}, {'name': 'Quadro P6000', 'memory_total': 25769803776}], 'memory': {'total': 31.279434204101562}}
2023-09-16 00:36:31,558 INFO    HandlerThread:2519239 [system_monitor.py:probe():211] Finished collecting system info
2023-09-16 00:36:31,558 INFO    HandlerThread:2519239 [system_monitor.py:probe():214] Publishing system info
2023-09-16 00:36:31,558 DEBUG   HandlerThread:2519239 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-09-16 00:36:31,560 DEBUG   HandlerThread:2519239 [system_info.py:_save_pip():68] Saving pip packages done
2023-09-16 00:36:31,560 DEBUG   HandlerThread:2519239 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-09-16 00:36:32,390 INFO    Thread-12 :2519239 [dir_watcher.py:_on_file_created():271] file/dir created: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/requirements.txt
2023-09-16 00:36:32,391 INFO    Thread-12 :2519239 [dir_watcher.py:_on_file_created():271] file/dir created: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/conda-environment.yaml
2023-09-16 00:36:33,644 DEBUG   HandlerThread:2519239 [system_info.py:_save_conda():87] Saving conda packages done
2023-09-16 00:36:33,647 INFO    HandlerThread:2519239 [system_monitor.py:probe():216] Finished publishing system info
2023-09-16 00:36:33,652 DEBUG   SenderThread:2519239 [sender.py:send():379] send: files
2023-09-16 00:36:33,652 INFO    SenderThread:2519239 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2023-09-16 00:36:33,666 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: stop_status
2023-09-16 00:36:33,666 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: stop_status
2023-09-16 00:36:33,668 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: internal_messages
2023-09-16 00:36:33,862 DEBUG   SenderThread:2519239 [sender.py:send():379] send: telemetry
2023-09-16 00:36:33,862 DEBUG   SenderThread:2519239 [sender.py:send():379] send: telemetry
2023-09-16 00:36:33,862 DEBUG   SenderThread:2519239 [sender.py:send():379] send: files
2023-09-16 00:36:33,862 INFO    SenderThread:2519239 [sender.py:_save_file():1375] saving file * with policy live
2023-09-16 00:36:34,174 INFO    wandb-upload_0:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/h0dnigcv-wandb-metadata.json
2023-09-16 00:36:34,254 INFO    wandb-upload_1:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/9cwsiook-config.yaml
2023-09-16 00:36:34,281 INFO    wandb-upload_2:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/cuh496ak-requirements.txt
2023-09-16 00:36:34,351 INFO    wandb-upload_3:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/x3ftf5nt-conda-environment.yaml
2023-09-16 00:36:34,364 INFO    wandb-upload_5:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/zri6j7ly-Entangled.py
2023-09-16 00:36:34,370 INFO    wandb-upload_4:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/112vc6v1-Detectron2_train.py
2023-09-16 00:36:34,380 INFO    wandb-upload_8:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/8up23cr2-README.md
2023-09-16 00:36:34,383 INFO    wandb-upload_7:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/1mwcwzze-Entangled_train.sh
2023-09-16 00:36:34,388 INFO    wandb-upload_10:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/n7aqdhj3-sweep_config.yml
2023-09-16 00:36:34,389 INFO    wandb-upload_6:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/r6il5v0u-Entangled.yml
2023-09-16 00:36:34,398 INFO    wandb-upload_9:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/8ni6je69-Torch_Custom_CNNs2.2.1.py
2023-09-16 00:36:34,624 INFO    wandb-upload_0:2519239 [upload_job.py:push():131] Uploaded file /tmp/tmpawmx1mnhwandb/i48nwjdf-wandb-metadata.json
2023-09-16 00:36:36,108 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: status_report
2023-09-16 00:36:38,616 DEBUG   SenderThread:2519239 [sender.py:send():379] send: telemetry
2023-09-16 00:36:38,616 DEBUG   SenderThread:2519239 [sender.py:send():379] send: exit
2023-09-16 00:36:38,616 INFO    SenderThread:2519239 [sender.py:send_exit():584] handling exit code: 1
2023-09-16 00:36:38,617 INFO    SenderThread:2519239 [sender.py:send_exit():586] handling runtime: 7
2023-09-16 00:36:38,618 INFO    SenderThread:2519239 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-16 00:36:38,618 INFO    SenderThread:2519239 [sender.py:send_exit():592] send defer
2023-09-16 00:36:38,619 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:38,619 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-16 00:36:38,619 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:38,619 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 0
2023-09-16 00:36:38,619 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 1
2023-09-16 00:36:38,619 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:38,619 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-16 00:36:38,619 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:38,619 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 1
2023-09-16 00:36:38,620 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 2
2023-09-16 00:36:38,620 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:38,620 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-16 00:36:38,620 INFO    HandlerThread:2519239 [system_monitor.py:finish():190] Stopping system monitor
2023-09-16 00:36:38,620 DEBUG   SystemMonitor:2519239 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-16 00:36:38,620 DEBUG   SystemMonitor:2519239 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-16 00:36:38,620 DEBUG   SystemMonitor:2519239 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-16 00:36:38,620 INFO    HandlerThread:2519239 [interfaces.py:finish():202] Joined cpu monitor
2023-09-16 00:36:38,621 INFO    HandlerThread:2519239 [interfaces.py:finish():202] Joined disk monitor
2023-09-16 00:36:38,780 INFO    HandlerThread:2519239 [interfaces.py:finish():202] Joined gpu monitor
2023-09-16 00:36:38,780 INFO    HandlerThread:2519239 [interfaces.py:finish():202] Joined memory monitor
2023-09-16 00:36:38,781 INFO    HandlerThread:2519239 [interfaces.py:finish():202] Joined network monitor
2023-09-16 00:36:38,781 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:38,781 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 2
2023-09-16 00:36:38,781 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 3
2023-09-16 00:36:38,781 DEBUG   SenderThread:2519239 [sender.py:send():379] send: stats
2023-09-16 00:36:38,782 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:38,782 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-16 00:36:38,782 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:38,782 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 3
2023-09-16 00:36:38,782 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 4
2023-09-16 00:36:38,782 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:38,782 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-16 00:36:38,782 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:38,782 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 4
2023-09-16 00:36:38,782 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 5
2023-09-16 00:36:38,782 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:38,782 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-16 00:36:38,783 DEBUG   SenderThread:2519239 [sender.py:send():379] send: summary
2023-09-16 00:36:38,785 INFO    SenderThread:2519239 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-16 00:36:38,785 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:38,785 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 5
2023-09-16 00:36:38,785 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 6
2023-09-16 00:36:38,786 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:38,786 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-16 00:36:38,786 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:38,786 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 6
2023-09-16 00:36:38,790 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: status_report
2023-09-16 00:36:39,249 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 7
2023-09-16 00:36:39,249 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:39,249 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-16 00:36:39,250 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:39,250 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 7
2023-09-16 00:36:39,617 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-16 00:36:40,394 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 8
2023-09-16 00:36:40,395 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: poll_exit
2023-09-16 00:36:40,395 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:40,395 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-16 00:36:40,396 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:40,396 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 8
2023-09-16 00:36:40,396 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 9
2023-09-16 00:36:40,396 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: defer
2023-09-16 00:36:40,396 INFO    HandlerThread:2519239 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-16 00:36:40,396 DEBUG   SenderThread:2519239 [sender.py:send_request():406] send_request: defer
2023-09-16 00:36:40,396 INFO    SenderThread:2519239 [sender.py:send_request_defer():608] handle sender defer: 9
2023-09-16 00:36:40,396 INFO    SenderThread:2519239 [dir_watcher.py:finish():358] shutting down directory watcher
2023-09-16 00:36:40,617 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-16 00:36:45,619 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 00:36:50,621 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 00:36:55,622 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 00:37:00,623 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 00:37:05,624 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 00:37:10,625 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 00:37:13,849 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-16 00:37:18,851 DEBUG   HandlerThread:2519239 [handler.py:handle_request():144] handle_request: keepalive
2023-09-16 00:37:19,969 WARNING StreamThr :2519239 [internal.py:is_dead():414] Internal process exiting, parent pid 2372321 disappeared
2023-09-16 00:37:19,969 ERROR   StreamThr :2519239 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-16 00:37:20,850 INFO    WriterThread:2519239 [datastore.py:close():294] close: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/run-yce7pjbq.wandb
2023-09-16 00:37:20,851 INFO    HandlerThread:2519239 [handler.py:finish():840] shutting down handler
2023-09-16 00:44:38,345 INFO    SenderThread:2519239 [dir_watcher.py:finish():388] scan: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files
2023-09-16 00:44:38,345 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/config.yaml config.yaml
2023-09-16 00:44:38,345 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/requirements.txt requirements.txt
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/conda-environment.yaml conda-environment.yaml
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/wandb-metadata.json wandb-metadata.json
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/Detectron2_train.py Detectron2_train.py
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/Entangled.py Entangled.py
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/Entangled.yml Entangled.yml
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/Entangled_train.sh Entangled_train.sh
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/README.md README.md
2023-09-16 00:44:38,346 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/Torch_Custom_CNNs2.2.1.py Torch_Custom_CNNs2.2.1.py
2023-09-16 00:44:38,347 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/sweep_config.yml sweep_config.yml
2023-09-16 00:44:38,347 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/output.log output.log
2023-09-16 00:44:38,347 INFO    SenderThread:2519239 [dir_watcher.py:finish():402] scan save: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/wandb-summary.json wandb-summary.json
2023-09-16 00:44:38,347 INFO    SenderThread:2519239 [sender.py:transition_state():612] send defer: 10
2023-09-16 00:44:38,348 INFO    SenderThread:2519239 [sender.py:finish():1531] shutting down sender
2023-09-16 00:44:38,348 INFO    SenderThread:2519239 [file_pusher.py:finish():175] shutting down file pusher
2023-09-16 00:44:38,348 INFO    SenderThread:2519239 [file_pusher.py:join():181] waiting for file pusher
2023-09-16 00:44:38,508 ERROR   wandb-upload_1:2519239 [internal_api.py:execute():361] 404 response executing GraphQL.
2023-09-16 00:44:38,509 ERROR   wandb-upload_1:2519239 [internal_api.py:execute():362] {"errors":[{"message":"run Elodea/yce7pjbq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-09-16 00:44:38,509 ERROR   Thread-11 :2519239 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpawmx1mnhwandb/nij73by7-config.yaml
Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2167, in upload_urls
    query_result = self.gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 330, in gql
    ret = self._retry_gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-16 00:44:39,146 ERROR   wandb-upload_7:2519239 [internal_api.py:execute():361] 404 response executing GraphQL.
2023-09-16 00:44:39,146 ERROR   wandb-upload_7:2519239 [internal_api.py:execute():362] {"errors":[{"message":"run Elodea/yce7pjbq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-09-16 00:44:39,146 ERROR   Thread-11 :2519239 [step_upload.py:_handle_event():200] Failed to upload file: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230916_003630-yce7pjbq/files/wandb-summary.json
Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2167, in upload_urls
    query_result = self.gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 330, in gql
    ret = self._retry_gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-16 00:44:39,163 ERROR   wandb-upload_3:2519239 [internal_api.py:execute():361] 404 response executing GraphQL.
2023-09-16 00:44:39,163 ERROR   wandb-upload_3:2519239 [internal_api.py:execute():362] {"errors":[{"message":"run Elodea/yce7pjbq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-09-16 00:44:39,164 ERROR   Thread-11 :2519239 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpawmx1mnhwandb/g79bgxxs-Entangled.py
Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2167, in upload_urls
    query_result = self.gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 330, in gql
    ret = self._retry_gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-16 00:44:39,178 ERROR   wandb-upload_8:2519239 [internal_api.py:execute():361] 404 response executing GraphQL.
2023-09-16 00:44:39,179 ERROR   wandb-upload_8:2519239 [internal_api.py:execute():362] {"errors":[{"message":"run Elodea/yce7pjbq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-09-16 00:44:39,179 ERROR   Thread-11 :2519239 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpawmx1mnhwandb/q0yz34s4-output.log
Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2167, in upload_urls
    query_result = self.gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 330, in gql
    ret = self._retry_gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-16 00:44:39,231 ERROR   wandb-upload_4:2519239 [internal_api.py:execute():361] 404 response executing GraphQL.
2023-09-16 00:44:39,231 ERROR   wandb-upload_4:2519239 [internal_api.py:execute():362] {"errors":[{"message":"run Elodea/yce7pjbq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-09-16 00:44:39,232 ERROR   Thread-11 :2519239 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpawmx1mnhwandb/2q0plg4t-Torch_Custom_CNNs2.2.1.py
Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2167, in upload_urls
    query_result = self.gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 330, in gql
    ret = self._retry_gql(
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/local/scratch/jrs596/envs/Entangled/lib/python3.8/site-packages/wandb/util.py", line 906, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-09-16 00:44:39,850 INFO    SenderThread:2519239 [file_stream.py:finish():594] file stream finish called
2023-09-16 00:44:39,972 INFO    SenderThread:2519239 [file_stream.py:finish():598] file stream finish is done
